// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxjulbzafjgjwxcnxccg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4anVsYnphZmpnand4Y254Y2NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODYwMzAsImV4cCI6MjA2NzA2MjAzMH0.VuLe0Xo0Z3nAvx2qRdAQVCIUKXERmbj9dn6OC_7MeLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});